# Site settings
title: byBorre
email: mail@byborre.com
description: > # this means to ignore newlines until "baseurl:"
  Creating concepts by proxy of fashion.
  Enhancing textiles by adding tactility.
  Taking the world by surprise.
  Designed by all means necessary.
  Made with love by far.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://byborre.github.io" # the base hostname & protocol for your site
twitter_username: byB0RRE
github_username:  byborre
facebook_username: byborre
instagram_username: byborre
markdown: redcarpet
highlighter: pygments
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty
collections:
  products:
    output: true
    permalink: /products/:path/
  projects:
    output: true
    permalink: /projects/:path/
